spring.application.name=cityscape-api
spring.datasource.url=jdbc:mysql://mysql-a316803-jothikakkl2004-1bc3.f.aivencloud.com:21704/defaultdb?useSSL=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_Cc8iQMCupV_GSwuUvBn
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

