spring.application.name=cityscape-api
spring.datasource.url=jdbc:mysql://localhost:3306/cityscape_db
spring.datasource.username=root
spring.datasource.password=ROOT
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false